name: lawsonmedia
favicon: null
layout_spectrum: 0.03987465053796768
typography_spectrum: 0.13340594922192395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.07475478714331985
  lightness: 0.8298263552132994
  saturation: 0.6521779980976135
  rhythmicContrast: 0.9598313798196614
purpose: []
